#!/bin/bash
#SBATCH --job-name=thesis/Slab/Doped/Structure/minimization
#SBATCH --nodes=1
#SBATCH  --ntasks-per-node=32
#SBATCH --time=48:00:00
#SBATCH --output=Log
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=rbao@caltech.edu 
module load intel/18.1 mkl/18.1

ulimit -s unlimited 
srun /central/groups/wag/programs/vasp.5.4.4/bin/vasp_std
